### ISSUE TITLE
regarding training dataset

### ISSUE THREAD

**Issue by sorobedio** [HSG-AIML/SANE#2]
Thank you for your excellent work.

Could you please provide the code to download and preprocess the dataset used in Table 4 with ResNet? Additionally, I need the code for the CNN-12k model referenced in Table 3. I would like to have the exact zoo for performance comparison.
Thank you!

**Comment by kschuerholt** [comment]
Thanks for reaching out, glad you found something interesting in our work! Apologies for the delayed response, ICML came in the way. 

I've added the scripts to preprocess the exact model zoos to /data. To download the full resnet model zoos and preprocess them using the scripts, you unfortunately have to go to modelzoos.cc and download the zips from gdrive. At the moment, this is the only feasible way for us to host the zoos since they're quite large. 

Feel free to reach out if you need assistance getting it working.

**Comment by sorobedio** [comment]
thank you  for your time.
